# ============================ filter_improved.yaml ============================
self_filter_ouster_horizontal:
  ros__parameters:
    sensor_frame: "airy_back_left_frame"

    # For spheres (single scale & padding)
    default_sphere_scale: 1.0
    default_sphere_padding: 0.01

    # For boxes (x,y,z scale & padding)
    default_box_scale: [1.0, 1.0, 1.0]
    default_box_padding: [0.01, 0.01, 0.01]

    # For cylinders (radial scale, vertical scale, radial padding, vertical padding)
    default_cylinder_scale: [1.0, 1.0]
    default_cylinder_padding: [0.01, 0.01]

    keep_organized: false
    zero_for_removed_points: false
    invert: false
    min_sensor_dist: 2.0

    # Link definitions
    self_see_links:
      names:
        - tower_cover

      tower_cover:
        box_scale: [1.0, 1.0, 1.0]
        box_padding: [0.05, 0.05, 0.05]